project:
  name: BiBs
  owner: parisepigenetics
  repo: https://github.com/parisepigenetics/bibs
  version: 1.0

attributions:
  rasflow_edc: Magali  
  
collections:
  facility:
    output: true
    permalink: "/:collection/:path/"
    title: Services
    tab-order: 1
  cluster:
    output: true
    permalink: "/:collection/:path/"
    title: HPC Clusters
    tab-order: 3
  edctools:
    output: true
    permalink: "/:collection/:path/"
    title: EDC tools
    tab-order: 2
  guidelines:
    output: true
    permalink: "/:collection/:path/"
    title: Guidelines
    tab-order: 4

highlighter: rouge
kramdown:
  footnote_backlink: "⮌"
permalink: pretty
sass:
  style: compressed
plugins:
- jemoji
- jekyll-remote-theme

remote_theme: pixeldroid/programming-pages
